services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    restart: unless-stopped

  postgres-server:
    image: postgres:16
    container_name: postgres-server
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "app"
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
volumes:
  postgres-data:
    driver: local

